name: Build and Deploy
on:
  push:
    paths:
      - 'docs/**'
      - '.github/workflows/vuepress-deploy.yml'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        TARGET_BRANCH: docs
        BUILD_SCRIPT: rm package.json && yarn add vuepress && npx vuepress build docs
        BUILD_DIR: docs/.vuepress/dist
